### ISSUE TITLE
Turing Completeness - pending at a workflow level

### ISSUE THREAD

**Issue by nmondal** [nmondal/flower#4]
We can not compute factorial.
I mean, technically we can, we can just create a nice script function as a body and it does would do it  -  something like this:

```yaml
fact:
   body:  |
      def fact(n){ /*  write here */ }
      fact(n) // call
```

But this is cheating.
We may want to have a way to support this w/o having a Turing Complete scripting extension.

There is another way - using fork and then just having a join to keep on multiplying the value out of the fork.
That also, feels like cheating.
What we are really saying is that there is a lack of "self-referential" structure with halting.
Should we have it? We do not know.

https://stackoverflow.com/questions/315340/practical-non-turing-complete-languages
